#!/bin/bash

if [[ ! -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -d "${UCVM_INSTALL_PATH}/model/cvms5/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/cvms5/lib:${DYLD_LIBRARY_PATH} ./test_cvms5
    exit
  fi
fi
env DYLD_LIBRARY_PATH=../src:${DYLD_LIBRARY_PATH} ./test_cvms5

